name: wallhub
description: "A beautiful wallpaper app with live wallpaper support built with Flutter."

# Prevents accidental publishing
publish_to: 'none'

# Version information
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  velocity_x: ^4.3.1
  google_fonts: ^6.3.1

  # State Management
  provider: ^6.1.5

  # HTTP & Network
  http: ^1.5.0
  dio: ^5.3.2

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0

  # Media & Video
  video_player: ^2.8.1

  # File & Storage
  path_provider: ^2.1.1
  path: ^1.8.3

  # Permissions & Device Info
  device_info_plus: ^9.1.0

  # Download & Save
  image_gallery_saver: ^2.0.3

  # File Operations
  open_filex: ^4.3.4

  # Sharing & Launch
  share_plus: ^7.2.1
  url_launcher: ^6.3.2

  # Wallpaper Setting
  async_wallpaper: ^2.1.0
  shared_preferences: ^2.2.3
  flutter_cache_manager: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets (uncomment and add your assets if needed)
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Custom fonts (uncomment and configure if needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
